# Generated by Django 5.0 on 2023-12-27 00:22

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_developer_genre_alter_game_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
