# Generated by Django 5.0 on 2023-12-27 01:32

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
    ]
