# Generated by Django 5.0 on 2023-12-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
