# Generated by Django 5.0 on 2023-12-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=200),
        ),
    ]
